services:
  mariadb:
    image: 8ct8pus/mariadb-alpine:1.1.0
    container_name: sandbox-db
    ports:
      - 3306:3306
    volumes:
      # expose mariadb config to host
      - ./docker/etc/:/docker/etc/
      # save mariadb databases to named volume
      - database:/var/lib/mysql/
  web:
    # php 8.4.4
    image: 8ct8pus/apache-php-fpm-alpine:2.4.1
    # php 8.4.1
    #image: 8ct8pus/apache-php-fpm-alpine:2.4.0
    # php 8.3.17
    #image: 8ct8pus/apache-php-fpm-alpine:2.3.3
    # php 8.3.13 RC1
    #image: 8ct8pus/apache-php-fpm-alpine:2.3.2
    # php 8.3.7 - iconv fix
    #image: 8ct8pus/apache-php-fpm-alpine:2.3.1
    # php 8.3.0
    #image: 8ct8pus/apache-php-fpm-alpine:2.2.0
    # php 8.2.11 with virtual hosts with new self-signed certificates generator
    #image: 8ct8pus/apache-php-fpm-alpine:2.1.3
    # php 8.2.10 with virtual hosts with new self-signed certificates generator
    #image: 8ct8pus/apache-php-fpm-alpine:2.1.2
    # php 8.2.9 with virtual hosts with new self-signed certificates generator
    #image: 8ct8pus/apache-php-fpm-alpine:2.1.1
    # php 8.2.8 with virtual hosts with new self-signed certificates generator
    #image: 8ct8pus/apache-php-fpm-alpine:2.1.0
    # php 8.2.7 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.12
    # php 8.2.5 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.11
    # php 8.2.4 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.10
    # php 8.2.3 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.9
    # php 8.2.2 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.8
    # php 8.2.1 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.7
    # php 8.2.0 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.6
    # php 8.1.12 with virtual hosts
    #image: 8ct8pus/apache-php-fpm-alpine:2.0.5
    hostname: sandbox
    container_name: sandbox
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/public
    links:
      - mariadb
    volumes:
      # development directory
      - ./sites/:/sites/
      # expose apache2 and php config to host
      - ./docker/etc/:/docker/etc/
volumes:
  database:
